### ISSUE TITLE
A tiny question on the code 

### ISSUE THREAD

**Issue by JiaQiSJTU** [GT-SALT/Multi-View-Seq2Seq#16]
line 265 in "Multi-View-Seq2Seq/fairseq_multi_view/fairseq/data/language_pair_dataset.py" :
'''
if self.src2 and self.src2[index][-2] == eos:
'''

Why "-2" instead of "-1" as in the line 262?  Thanks a lot!

**Comment by jiaaoc** [comment]
That should be a typo. It should be -1.
