### ISSUE TITLE
Could you elaborate on how to evaluate topic segmentation task?

### ISSUE THREAD

**Issue by lifelongeek** [GT-SALT/Multi-View-Seq2Seq#5]
Hi. 
Thanks for sharing interesting work with the community 👍 
I am trying to understand and see how combination of sentence-transformer embedding and C99 works for topic segmentation.
For example, I get 7 topic segments from running Topic_Segment.ipynb

```
Segment 1. A: Hi Tom, are you busy tomorrow’s afternoon?
Segment 2. B: I’m pretty sure I am. What’s up?, A: Can you go with me to the animal shelter?., B: What do you want to do?
Segment 3. A: I want to get a puppy for my son., 'B: That will make him so happy., A: Yeah, we’ve discussed it many times. I think he’s ready now., 
Segment 4. B: That’s good. Raising a dog is a tough issue. Like having a baby ;-), A: I'll get him one of those little dogs." 
Segment 5. B: One that won't grow up too big;-), A: And eat too much;-)), B: Do you know which one he would like? 
Segment 6. A: Oh, yes, I took him there last Monday. He showed me one that he really liked., B: I bet you had to drag him away., A: He wanted to take it home right away ;-)., 
Segment 7. B: I wonder what he'll name it., A: He said he’d name it after his dead hamster – Lemmy  - he's  a great Motorhead fan :-)))

```

Could you suggest any tip for evaluating the quality segmentation of above example?
As I understand, you decide the hyperparameter for C99 (window size 4 and std coefficient 1) with qualitative evaluation with several human. Personally, I think that "topic segmentation" is a difficult problem in which people think of the correct segmentation boundary differently.  So if you elaborate on how such qualitative evaluation is done, it would be much helpful for the research community :)

**Comment by jiaaoc** [comment]
We did not do the qualitative evaluation with several human in a large scale. Instead, I manually checked around 25 segmented results to see if I could summarize meaningful topics from segments and there did not exist large overlaps.
