### ISSUE TITLE
Why the segmentation of the stage view in the demo in the paper is different from the test set

### ISSUE THREAD

**Issue by PYMAQ** [GT-SALT/Multi-View-Seq2Seq#7]
This is generated from the source code：test_sent_trans_cons_label.source
| James: Hey! I’ve been thinking about you ;)  
| Hannah: Oh, that’s nice ;) 
| James: what are you up to? Hannah: i'm about to sleep  James: I miss u I was hoping to see you  Hannah: have to get up early for work tomorrow James: what about tomorrow?  Hannah: to be honest i have plans for tomorrow evening James: oh ok, what about Sat then? Hannah: yeah, sure i’m available on sat James: i’ll pick you up at 8? 
| Hannah: sounds good. See u then.

Is the segmentation area different from the demo in the paper?：
this is from the Table 1 from paper
| James: Hey! I’ve been thinking about you ;)  
Hannah: Oh, that’s nice ;) 
James: what are you up to? 
| Hannah: i'm about to sleep  James: I miss u I was hoping to see you  
| Hannah: have to get up early for work tomorrow James: what about tomorrow?  Hannah: to be honest i have plans for tomorrow evening James: oh ok, what about Sat then? Hannah: yeah, sure i’m available on sat James: i’ll pick you up at 8? 
| Hannah: sounds good. See u then.

thank you！~

**Comment by jiaaoc** [comment]
Hi, this might be due to the randomness of GaussianHMM. I think even it might be different on single data points, but the general pattern should keep the same.

**Comment by PYMAQ** [comment]
ok it might be the randomness of GaussianHMM.
thank you for your patience~
