### ISSUE TITLE
Error(s) in loading state_dict for BARTModel

### ISSUE THREAD

**Issue by engindeniz** [GT-SALT/Multi-View-Seq2Seq#8]
I have the same problem with #6. I installed fairseq as you suggested.  There are required two paths for pretrained model, I defined them as follows:

- **checkpoint_file:** I downloaded your model from [here](https://drive.google.com/file/d/1Rhzxk1B7oaKi85Gsxr_8WcqTRx23HO-y/view).

- **data_name_or_path**:  "Multi-View-Seq2Seq/train_sh/cnn_dm-bin_2/" (It is already in the repo)

Could you suggest any solution?

**Comment by jiaaoc** [comment]
The errors look like the models you installed from fairseq do not have some modules in the pre-trained model (like the "w_proj"). I would suggest checking the installed faieseq.

**Comment by jiaaoc** [comment]
For a quick check, I would suggest random initializing a Bart model and checking its named parameters.

**Comment by engindeniz** [comment]
When I load the [BART pretrained](https://dl.fbaipublicfiles.com/fairseq/models/bart.large.cnn.tar.gz) model,  I can load without any error.  I think that mismatch of named parameters is between your pretrained model and the Bart model.  Could you check it, please? Btw, I am using "Eval_Sum.ipynb".

**Comment by jiaaoc** [comment]
> When I load the BART pretrained model, I can load without any error. I think that mismatch of named parameters is between your pretrained model and the Bart model. Could you check it, please? Btw, I am using "Eval_Sum.ipynb".

In this case, it seems that the fairseq you are using in the notebook is not correct. As our model indeed is different from original BART.

**Comment by engindeniz** [comment]
I uninstalled and installed it again. It is working now. I don't know what happened exactly before. It might about my conda configuration. 
Thank you so much for your response.
